spring:
  application:
    name: ASE251S4_T11-be
  data:
    mongodb:
      uri: mongodb+srv://gianherrera_db_user:vZSohpapGRtE7sNP@cluster0.0dvnx1x.mongodb.net/agrimarket
      connection-string: mongodb+srv://gianherrera_db_user:vZSohpapGRtE7sNP@cluster0.0dvnx1x.mongodb.net/agrimarket
      database: agrimarket
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

agrimarket:
  mongodb:
    connection-string: mongodb+srv://gianherrera_db_user:vZSohpapGRtE7sNP@cluster0.0dvnx1x.mongodb.net/agrimarket
    database: agrimarket

server:
  port: 8080