spring:
  application:
    name: ASE251S4_T11-be
  data:
    mongodb:
      uri: ${MONGODB_URI}
      connection-string: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:Agrimarket}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

agrimarket:
  mongodb:
    connection-string: ${MONGODB_URI}
    database: ${MONGODB_DATABASE:Agrimarket}

server:
  port: ${SERVER_PORT:8080}