apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://brandoflores_db_user:e2iOpvB3lPUdvda6 @cluster0.pofa1rg.mongodb.net/"
  SQLSERVER_HOST: "localhost"
  SQLSERVER_PORT: "1433"
  SQLSERVER_USER: "sa"
  SQLSERVER_PASSWORD: "Sql12345678!"
  SQLSERVER_DATABASE: "Agrimarket"
