apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: brando-lucana-agrimarket-be
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://brandoflores_db_user:e2iOpvB3lPUdvda6@cluster0.pofa1rg.mongodb.net/"
  MONGODB_DATABASE: "Agrimarket"
