apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://gianAdmin:9523HER@agrimarket.ir643.mongodb.net/?retryWrites=true&w=majority&appName=Agrimarket"
