apiVersion: v1
kind: Service
metadata:
  name: gian-herrera-11-service
  namespace: gian-herrera-11-namespace
spec:
  type: NodePort
  selector:
    app: gian-herrera-11-deployment
  ports:
    - port: 8080        # puerto interno del Service
      targetPort: 8080  # puerto del contenedor
      nodePort: 30080   # puerto externo en tu máquina
